import React, { Suspense } from 'react';
import { useParams, Link as RouterLink } from 'react-router-dom';
import { Box, Typography, Card, CardContent, Stack, Chip } from '@mui/material';
import { GENERATED_PAGES, GeneratedPageKind } from './generated/registry';
import LoadingSkeleton from '../components/common/LoadingSkeleton';

const KIND_COLOR: Record<GeneratedPageKind, string> = {
  trip:    '#26A69A',
  project: '#90A4AE',
  report:  '#FFCA28',
  plan:    '#5B8DEF',
  persona: '#9C7BFF',
  other:   '#7d8590',
};

const SpacesIndex: React.FC = () => {
  const visible = GENERATED_PAGES.filter(p => !p.hidden);
  return (
    <Box>
      <Box sx={{ mb: 3 }}>
        <Typography variant="h4" fontWeight={700}>Spaces</Typography>
        <Typography variant="body2" color="text.secondary" sx={{ mt: 0.5 }}>
          Pages generated by your agents — trips, project hubs, weekly reports.
        </Typography>
      </Box>
      {visible.length === 0 ? (
        <Card sx={{ '&:hover': { transform: 'none' }, py: 4, textAlign: 'center' }}>
          <Typography variant="body2" color="text.secondary">
            No spaces yet. When an agent generates a page, it shows up here.
          </Typography>
        </Card>
      ) : (
        <Stack spacing={1.5}>
          {visible.map(p => (
            <RouterLink key={p.slug} to={`/spaces/${p.slug}`} style={{ textDecoration: 'none' }}>
              <Card
                sx={{
                  '&:hover': { transform: 'translateY(-2px)' },
                  borderLeft: `3px solid ${KIND_COLOR[p.kind]}`,
                  cursor: 'pointer',
                }}
              >
                <CardContent sx={{ py: 2 }}>
                  <Box sx={{ display: 'flex', alignItems: 'center', gap: 1.5 }}>
                    <Typography sx={{ fontSize: 22 }}>{p.emoji}</Typography>
                    <Box sx={{ flex: 1, minWidth: 0 }}>
                      <Typography variant="body1" fontWeight={600}>{p.title}</Typography>
                      {p.summary && (
                        <Typography variant="caption" color="text.secondary" sx={{ display: 'block', mt: 0.25, fontSize: '0.78rem' }}>
                          {p.summary}
                        </Typography>
                      )}
                    </Box>
                    <Stack direction="row" spacing={0.5} alignItems="center">
                      <Chip
                        size="small"
                        label={p.kind}
                        sx={{
                          height: 20, fontSize: '0.65rem',
                          textTransform: 'capitalize',
                          color: KIND_COLOR[p.kind],
                          bgcolor: `${KIND_COLOR[p.kind]}1a`,
                        }}
                      />
                      <Typography variant="caption" color="text.secondary" sx={{ fontSize: '0.7rem', display: { xs: 'none', sm: 'inline' } }}>
                        {p.author}
                      </Typography>
                    </Stack>
                  </Box>
                </CardContent>
              </Card>
            </RouterLink>
          ))}
        </Stack>
      )}
    </Box>
  );
};

const SpacesViewer: React.FC = () => {
  const { slug } = useParams<{ slug: string }>();
  const entry = GENERATED_PAGES.find(p => p.slug === slug);

  if (!entry) {
    return (
      <Box>
        <Typography variant="h5" fontWeight={700}>Space not found</Typography>
        <Typography variant="body2" color="text.secondary" sx={{ mt: 1 }}>
          No generated page registered for slug "{slug}". Check{' '}
          <code>src/pages/generated/registry.ts</code>.
        </Typography>
        <Typography variant="body2" sx={{ mt: 2 }}>
          <RouterLink to="/spaces">← Back to all spaces</RouterLink>
        </Typography>
      </Box>
    );
  }

  const Page = entry.component;
  return (
    <Suspense fallback={<LoadingSkeleton variant="card" count={3} />}>
      <Page />
    </Suspense>
  );
};

interface Props {
  /** When true, render the index. When false, render the routed slug. */
  index?: boolean;
}

const SpacesPage: React.FC<Props> = ({ index = false }) => index ? <SpacesIndex /> : <SpacesViewer />;

export default SpacesPage;
